{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    app: {{ .Chart.Name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}